### ISSUE TITLE
Naked domain DNS records

### ISSUE THREAD

**Issue by tomgoren** [gatks/croc.farm#7]
Pointing "naked" (a.k.a. "apex", or "root") domain to a site is very difficult in GCP.

We can't use the static website storage, because [that relies on a CNAME](https://cloud.google.com/storage/docs/hosting-static-website). Same goes for Cloud Functions.

CNAMEs are not supported for the naked domain, and in the serverless option we can't use server-side forwarding.

Anyway, in the spirit of getting something working I'm trying one last option.

**Comment by tomgoren** [comment]
Figured it out.

To do a "Hello World", all I had to do was:
* Create a default website Docker image based on the official Nginx image
* Create a static web page, e.g. `index.html`
* Build the image
* Push the image to the GCP registry
* Create a Kubernetes cluster in GCP
* Create a `Deployment` that uses the image above
* Configure a `Service` that defines a load balancer that points traffic to the exposed port 80 on the running container
* Create an A record for the naked domain that points to the load balancer's IP

Easy!

![croc_farm_hello_world](https://user-images.githubusercontent.com/806975/37068248-c707e1f0-217b-11e8-968d-1cb2dab12a9b.png)

**Comment by tomgoren** [comment]
P.S. The nice thing about this approach is that it sets the stage almost completely from the Infrastructure perspective for an _actual_ service.

We can avoid the serverless option for now, and just use a more traditional approach for starters.

It's better practice for me anyhow.

**Comment by amireldor** [comment]
Please check pricing for this. Using the Google calculator showed very large costs unless I computed something wrong.

It shouldn't cost more than $5 a month. Cloud Functions help with that lowering that even further but I see the CNAME problem is with functions too. This is really stupid.

**Comment by tomgoren** [comment]
For starters we have 300$ credit towards a first year of Google mania.

In order to make it stretch a bit, I just adjusted the VM type and storage size to the cheapest available.

I don't think we have to worry about this aspect just yet, and instead just make things work as quickly as possible.

**Comment by amireldor** [comment]
ok
